### ISSUE TITLE
Stack compatibility

### ISSUE THREAD

**Issue by dawei-dev** [zohl/dictionaries#1]
Hello thanks for creating this small but wonderful library.

Could you make you library compatible with stack?
I can not build it because of library version issues:

```
$ stack install dictionaries

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for dictionaries-0.1.0.0:
    binary-0.8.3.0 must match >=0.7.5 && <0.8 (latest applicable is 0.7.6.1)
    directory-1.3.0.0 must match >=1.2.2 && <1.3 (latest applicable is 1.2.7.1)
    time-1.6.0.1 must match >=1.5.0 && <1.6 (latest applicable is 1.5.0.1)

Plan construction failed.
```

**Comment by zohl** [comment]
Hello,

Sure, I'll fix it in a day or two.

**Comment by zohl** [comment]
I've updated bounds and created pull request on stackage[1]. Sorry for the delay, I guess, it will take time to approve it, but you can try to use the new version of the package (`0.1.0.1`) from hackage.

[1] https://github.com/fpco/stackage/pull/2374

**Comment by dawei-dev** [comment]
Great! Thanks a lot!
